In [1]:
import atom_numbering as an
import pandas as pd
import get_xyz_descriptors_original as xyz
import os
import numpy as np

In [2]:
#Provide path to directory or directory of directies containing xyz files
path = "/home/aconner/orca_descriptors/AATATIAROAAKIN-SNVBAGLBSA-N/"

#Compile dataframe with atom numberings; Can specify 0 or 1 indexing for atom numberings and whether to search subdirectories or main diertory only defaults to 1 indexing and searching subdirectories
df = an.compile_final(path) 
df

,xyz_name,path,ligand_type,inchi,SCF_energy,smiles,H1,Ni,H2,N1,C1,C2,N2,ligand_class
0,optimization,/home/aconner/orca_descriptors/AATATIAROAAKIN-...,core_5,AATATIAROAAKIN-SNVBAGLBSA-N,-2497.275344,[H]C1=C(C(F)(F)F)C([H])=C([H])C(=C2N[C@@]([H])...,1,2,3,15,6,5,4,pyox
1,optimization,/home/aconner/orca_descriptors/AATATIAROAAKIN-...,core_5,AATATIAROAAKIN-SNVBAGLBSA-N,-2497.275319,[H]C1=C(C(F)(F)F)C([H])=C([H])C(=C2N[C@@]([H])...,1,2,3,15,6,5,4,pyox

In [3]:
#Define lists for decriptor retrieval 
atoms = ["H1", "H2", "C1", "C2", "N1", "N2", "Ni"]
bonds = [("C1", "N1"), ("N1", "C1"), ("C2", "N2"), ("N2", "C2"), ("Ni", "N1"), ("Ni", "N2"), ("Ni", "H1"), ("Ni", "H2")] #if order matters for 2-atom descriptors (e.g. Sterimol B1), atoms must be listed in desired order
angles = [("H2", "Ni", "H1")]
dihedrals = [("N1", "C1", "C2", "N2"), ("C2", "N2", "Ni", "H2"), ("C1", "N1", "Ni", "H1")]

#quadrants = [[2, 1, 3, 4, 6]]

In [5]:
#generate descriptor dictionary for each row in dataframe and add to dataframe
results_dict = {}
for row in df.itertuples():

    P = xyz.PropertiesXYZ(path=df.loc[row.Index, "path"])
    
    #Zero atom properties
    P.get_SASA_and_Volume()

    #One atom properties
    atom_list = []
    for atom in atoms:
        atom_list.append(int(df.loc[row.Index, atom]))
    
    P.define_atom_list(atom_list)
    P.get_Vbur()
    P.get_atomic_SASA()

    #Two atom properties
    bond_list = []
    for bond in bonds: 
        bond_list.append([int(df.loc[row.Index, bond[0]]), int(df.loc[row.Index, bond[1]])])
    P.define_bond_list(bond_list)
    P.get_bond_distances()
    P.get_Sterimol_parameters()

    #Three atom properties
    angle_list = []
    for angle in angles:
        angle_list.append([int(df.loc[row.Index, angle[0]]), int(df.loc[row.Index, angle[1]]), int(df.loc[row.Index, angle[2]])])
    P.define_angle_list(angle_list)
    P.get_angles()

    #Four atom properties
    dihedral_list = []
    for dihedral in dihedrals:
        dihedral_list.append([int(df.loc[row.Index, dihedral[0]]), int(df.loc[row.Index, dihedral[1]]), int(df.loc[row.Index, dihedral[2]]), int(df.loc[row.Index, dihedral[3]])])
    P.define_dihedral_list(dihedral_list)
    P.get_dihedrals()
    #P.get_pyramidalizations()

    #Quadrant properties
    #quadrant_list = quadrants
    #P.define_quadrant_list(quadrant_list)
    #P.get_vbur_quadrants()
    #P.get_vbur_octants()

    results_dict[row.Index] = P.results

No xyz.json file found in the specified path. Results dictionary will be empty.
   /home/aconner/orca_descriptors/AATATIAROAAKIN-SNVBAGLBSA-N/conf_2/optimization.xyz / Bmin:  2.35 / Bmax:  7.59 / L:  4.80
   /home/aconner/orca_descriptors/AATATIAROAAKIN-SNVBAGLBSA-N/conf_2/optimization.xyz / Bmin:  2.35 / Bmax:  7.59 / L:  5.15
   /home/aconner/orca_descriptors/AATATIAROAAKIN-SNVBAGLBSA-N/conf_2/optimization.xyz / Bmin:  2.31 / Bmax:  7.54 / L:  5.40
   /home/aconner/orca_descriptors/AATATIAROAAKIN-SNVBAGLBSA-N/conf_2/optimization.xyz / Bmin:  2.31 / Bmax:  7.54 / L:  6.05
   /home/aconner/orca_descriptors/AATATIAROAAKIN-SNVBAGLBSA-N/conf_2/optimization.xyz / Bmin:  2.56 / Bmax:  6.81 / L:  7.35
   /home/aconner/orca_descriptors/AATATIAROAAKIN-SNVBAGLBSA-N/conf_2/optimization.xyz / Bmin:  2.49 / Bmax:  7.65 / L:  6.50
   /home/aconner/orca_descriptors/AATATIAROAAKIN-SNVBAGLBSA-N/conf_2/optimization.xyz / Bmin:  2.85 / Bmax:  6.88 / L:  3.70
   /home/aconner/orca_descriptors/AATATIAROAAKIN-SNVBAGLBSA-N/conf_2/optimization.xyz / Bmin:  2.59 / Bmax:  7.64 / L:  4.15
No xyz.json file found in the specified path. Results dictionary will be empty.
   /home/aconner/orca_descriptors/AATATIAROAAKIN-SNVBAGLBSA-N/conf_1/optimization.xyz / Bmin:  2.39 / Bmax:  7.60 / L:  4.80
   /home/aconner/orca_descriptors/AATATIAROAAKIN-SNVBAGLBSA-N/conf_1/optimization.xyz / Bmin:  2.39 / Bmax:  7.60 / L:  5.15
   /home/aconner/orca_descriptors/AATATIAROAAKIN-SNVBAGLBSA-N/conf_1/optimization.xyz / Bmin:  2.34 / Bmax:  7.54 / L:  5.40
   /home/aconner/orca_descriptors/AATATIAROAAKIN-SNVBAGLBSA-N/conf_1/optimization.xyz / Bmin:  2.34 / Bmax:  7.54 / L:  6.05
   /home/aconner/orca_descriptors/AATATIAROAAKIN-SNVBAGLBSA-N/conf_1/optimization.xyz / Bmin:  2.64 / Bmax:  6.82 / L:  7.45
   /home/aconner/orca_descriptors/AATATIAROAAKIN-SNVBAGLBSA-N/conf_1/optimization.xyz / Bmin:  2.50 / Bmax:  7.74 / L:  6.50
   /home/aconner/orca_descriptors/AATATIAROAAKIN-SNVBAGLBSA-N/conf_1/optimization.xyz / Bmin:  2.61 / Bmax:  7.74 / L:  4.10
   /home/aconner/orca_descriptors/AATATIAROAAKIN-SNVBAGLBSA-N/conf_1/optimization.xyz / Bmin:  2.82 / Bmax:  6.86 / L:  3.70

In [6]:
dict_atoms = {}
for row in df.itertuples():
    dict_atoms[row.Index] = {}
    for col in df.columns:
        if col.startswith("H1"):
            atom = col[:-1] 
            number = df.at[row.Index, col]
            dict_atoms[row.Index][col] = atom + str(number)
        elif col.startswith("H2"):
            atom = col[:-1] 
            number = df.at[row.Index, col]
            dict_atoms[row.Index][col] = atom + str(number)
        elif col.startswith("C1"):
            atom = col[:-1] 
            number = df.at[row.Index, col]
            dict_atoms[row.Index][col] = atom + str(number)
        elif col.startswith("C2"):
            atom = col[:-1] 
            number = df.at[row.Index, col]
            dict_atoms[row.Index][col] = atom + str(number)
        elif col.startswith("N1"):
            atom = col[:-1] 
            number = df.at[row.Index, col]
            dict_atoms[row.Index][col] = atom + str(number)
        elif col.startswith("N2"):
            atom = col[:-1] 
            number = df.at[row.Index, col]
            dict_atoms[row.Index][col] = atom + str(number)
        elif col.startswith("Ni"):
            atom = col  
            number = df.at[row.Index, col]
            dict_atoms[row.Index][col] = atom + str(number)

In [7]:
#alter key in results dictionary to match format of user defined lists and add to dataframe
#Have to add new descriptors to this code!!
new_results = {}

for key in results_dict.keys():
    new_results[key] = {}
    for subkey in results_dict[key].keys():
        if subkey.startswith("Bond_"):
            for bond in bonds:
                bond_key = [dict_atoms[key][bond[0]], dict_atoms[key][bond[1]]]
                if all(bk in subkey for bk in bond_key):
                    new_key = "Bond_" + bond[0] + "_" + bond[1]
                    new_results[key][new_key] = results_dict[key][subkey]
        elif subkey.startswith("Sterimol_") and subkey.endswith("_L"):
            for bond in bonds:
                bond_key = [dict_atoms[key][bond[0]], dict_atoms[key][bond[1]]]
                if all(bk in subkey for bk in bond_key):
                    new_key = "Sterimol_" + bond[0] + "_" + bond[1] +"_L"
                    new_results[key][new_key] = results_dict[key][subkey]
        elif subkey.startswith("Sterimol_") and subkey.endswith("_Bmin"):
            for bond in bonds:
                bond_key = [dict_atoms[key][bond[0]], dict_atoms[key][bond[1]]]
                if all(bk in subkey for bk in bond_key):
                    new_key = "Sterimol_" + bond[0] + "_" + bond[1] +"_Bmin"
                    new_results[key][new_key] = results_dict[key][subkey]
        elif subkey.startswith("Sterimol_") and subkey.endswith("_Bmax"):
            for bond in bonds:
                bond_key = [dict_atoms[key][bond[0]], dict_atoms[key][bond[1]]]
                if all(bk in subkey for bk in bond_key):
                    new_key = "Sterimol_" + bond[0] + "_" + bond[1] +"_Bmax"
                    new_results[key][new_key] = results_dict[key][subkey]
        elif subkey.startswith("Angle_"):
            for angle in angles:
                angle_key = [dict_atoms[key][angle[0]], dict_atoms[key][angle[1]], dict_atoms[key][angle[2]]]
                if all(ak in subkey for ak in angle_key):
                    new_key = "Angle_" + angle[0] + "_" + angle[1] + "_" + angle[2]
                    new_results[key][new_key] = results_dict[key][subkey]
        elif subkey.startswith("Dihed_"):
            for dihedral in dihedrals:
                dihedral_key = [dict_atoms[key][dihedral[0]], dict_atoms[key][dihedral[1]], dict_atoms[key][dihedral[2]], dict_atoms[key][dihedral[3]]]
                if all(dk in subkey for dk in dihedral_key):
                    new_key = "Dihed_" + dihedral[0] + "_" + dihedral[1] + "_" + dihedral[2] + "_" + dihedral[3]
                    new_results[key][new_key] = results_dict[key][subkey]
        elif subkey.startswith("%Vbur_atom_"):
            for atom in atoms:
                atom_key = dict_atoms[key][atom]
                if atom_key in subkey:
                    new_key = "%Vbur_" + atom
                    new_results[key][new_key] = results_dict[key][subkey]
        elif subkey.startswith("SASA_"):
            for atom in atoms:
                atom_key = dict_atoms[key][atom]
                if atom_key in subkey:
                    new_key = "SASA_" + atom
                    new_results[key][new_key] = results_dict[key][subkey]
        else:
            new_results[key][subkey] = results_dict[key][subkey]

In [8]:
#add new results to dataframe
for key in new_results.keys():
    for subkey in new_results[key].keys():
        df.at[key, subkey] = new_results[key][subkey]

df

,xyz_name,path,ligand_type,inchi,SCF_energy,smiles,H1,Ni,H2,N1,...,Sterimol_Ni_H1_Bmin,Sterimol_Ni_H1_Bmax,Sterimol_Ni_H1_L,Sterimol_Ni_H2_Bmin,Sterimol_Ni_H2_Bmax,Sterimol_Ni_H2_L,Angle_H2_Ni_H1,Dihed_N1_C1_C2_N2,Dihed_C2_N2_Ni_H2,Dihed_C1_N1_Ni_H1
0,optimization,/home/aconner/orca_descriptors/AATATIAROAAKIN-...,core_5,AATATIAROAAKIN-SNVBAGLBSA-N,-2497.275344,[H]C1=C(C(F)(F)F)C([H])=C([H])C(=C2N[C@@]([H])...,1,2,3,15,...,2.84832,6.880770,3.7,2.588150,7.638881,4.15,81.058632,2.174222,-65.194294,110.863428
1,optimization,/home/aconner/orca_descriptors/AATATIAROAAKIN-...,core_5,AATATIAROAAKIN-SNVBAGLBSA-N,-2497.275319,[H]C1=C(C(F)(F)F)C([H])=C([H])C(=C2N[C@@]([H])...,1,2,3,15,...,2.60637,7.740317,4.1,2.817871,6.861669,3.70,81.072192,2.468409,-166.767241,170.039821

In [9]:
#Find min, max, and average of descriptors across dataset
descriptor_stats = {}

#boltzmann weighted average
#convert energy to relative energy
if 'Relative_energy' not in df.columns:
    df.insert(5, 'Relative_energy', df['SCF_energy'] - df['SCF_energy'].min())
else:
    df['Relative_energy'] = df['SCF_energy'] - df['SCF_energy'].min()


T = 298.15 #temperature in K
R = 3.1668105e-6 #Boltzmann constant in eH/K
weights = []

for row in df.itertuples():
    energy = row.Relative_energy
    weight = np.exp(-energy/(R*T))
    weights.append(weight)

normalized_weights = weights / np.sum(weights)

for column in df.iloc[:, 15:]:
    descriptor_stats[f'{column}_min'] = df[column].min()
    descriptor_stats[f'{column}_max'] = df[column].max()
    descriptor_stats[f'{column}_mean'] = np.average(df[column], weights=normalized_weights)

descriptor_stats_df = pd.DataFrame(descriptor_stats, index=[0])
if df["smiles"].nunique() == 1:
    descriptor_stats_df.insert(0, "SMILES", df["smiles"].iloc[0])
    descriptor_stats_df.insert(1, "INCHI", df["inchi"].iloc[0])
else:
    print("Multiple SMILES strings found in dataset. Please seperate before calculating descriptor statistics.")    


descriptor_stats_df.to_csv("descriptor_stats.csv", index=False)
os.rename("descriptor_stats.csv", f"{df['inchi'].iloc[0]}.csv")